[package]
name = "alice-open-data"
version = "0.2.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
description = "Tools to download and manage the publicly released ALICE open data"
repository = "https://github.com/cbourjau/alice-rs"
readme = "README.md"
keywords = ["cern", "alice", "lhc", "physics", "data"]
categories = ["science"]
license = "MPL-2.0"


[dependencies]
glob = "^0.2.11"
failure = "0.1.1"
reqwest = "0.8.5"
