[package]
name = "malice"
version = "0.1.1"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
exclude = ["benches/*"]
description = "A small framwork providing sensible defaults to analyse ALICE's open data"
repository = "https://github.com/cbourjau/alice-rs/malice"
readme = "README.md"
keywords = ["root", "cern", "alice", "lhc", "physics"]
categories = ["science", "data-structures"]
license = "MPL-2.0"

[features]
default = []
cpp = ["alice-sys"]

[dependencies]
nom = "4"
root-io = { path = "../root-io" }
failure = "0.1.1"
bitflags = "1.0.1"

# Optional dependencies
alice-sys = { version="0.1.1", optional = true }

[dev-dependencies]
alice-open-data = "0.2.0"

[[bench]]
name = "rust_vs_root"
harness = false
