[package]
name = "simple-analysis"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
workspace = "../../"

[dependencies]
malice = "0.1.0"
root-io = "0.1.1"
alice-open-data = "0.2.0"
gnuplot = "^0.0.22"
histogram = {path = "../../histogram" }
failure = "0.1.1"
