[package]
name = "convert_to_json"
version = "0.1.0"
authors = ["cbourjau <christian.bourjau@cern.ch>"]

[dependencies]
malice = "0.1.0"
alice-open-data = "0.2.0"
root-io = "0.1.1"
serde = "1.0"
serde_json = "1.0"
