[package]
name = "alice-download"
version = "0.1.1"
authors = ["cbourjau <christian.bourjau@cern.ch>"]
description = "CLI tool to download a given amount of the publicly released ALICE open data"
repository = "https://github.com/cbourjau/alice-rs"
readme = "README.md"
keywords = ["cern", "alice", "lhc", "physics", "data"]
categories = ["science"]
license = "MPL-2.0"

[dependencies]
indicatif = "^0.6.0"
clap = "^2"
alice-open-data = "0.2.0"
failure = "0.1.1"
